### ISSUE TITLE
Error in gain set

### ISSUE THREAD

**Issue by aghsieh** [dansteingart/serveSIUI#1]
When trying to set gain, most values seem fine, but the following errors occur (there may be more, but these are the ones I noticed):

desired gain --> resulting gain
76.5 --> 102.1
76.6 --> 102.2
76.7 --> 102.3

This occurs in both dual and single mode.

76.1-76.4 dB and 76.8, 76.9 are all okay.

**Comment by dansteingart** [comment]
It has to do with how the bits are set.  that's an edge case for sure, but let me try to fix it:

``` python

#take SIUI bytes to string
def stov(s1,s2):
    return (255*s2 + s1+s2)/10.0
#take bytes to siui

def vtos(v):
    v = int(v*10)
    b2 = v/255
    b1 = v%255 - b2
    return [b1,b2]
```

going to try to fix

**Comment by dansteingart** [comment]
this should fix it https://github.com/dansteingart/serveSIUI/commit/697bb2fec1e2b0fb9772c6c60970d078db3660f6, or at least knock it to a similar value.

**Comment by dansteingart** [comment]
That didn't fully fix it, it's because I'm converting to a short int not a long int.  will try to fix properly now.

**Comment by dansteingart** [comment]
meh, don't feel like fixing it now.  if it comes back to haunt us I'll fix it better.
