### ISSUE TITLE
uint8 vs uint16 for different rectification modes?

### ISSUE THREAD

**Issue by gregdavies** [dansteingart/serveSIUI#4]
When the unit is set to 'filter' mode in rectification, the output appears to be in uint16.

When the unit is set to 'rf' mode in rectification, the output appears to be in uint8.

Not sure about other rectification modes.

**Comment by dansteingart** [comment]
@gregdavies you mean uint8 works better for some and uint16 works better for others, right?   I'll add a change so you can call either and store the raw data.  O we just use uint8 and upconvert to 16 when need be.

**Comment by dansteingart** [comment]
I added a wave8 and wave16 dictionary element.  Also, saving the raw data instead /along with the formatted json will allow us to go back and reprocess if necessary.
