### ISSUE TITLE
Pulse location and probe thickness

### ISSUE THREAD

**Issue by gregdavies** [dansteingart/serveSIUI#6]
The pulse given by the unit starts its rise at 0us, therefore the initial pulse is actually centered after 0uS.

Additionally, there is a finite thickness of ceramic over the top of the transducer, and therefore a reflection from the transducer/material interface is seen shortly after the pulse. In essence, half way between these two peaks (pulse and interface reflection) is the point at which the signal t = 0.

Also worthwhile to note that the signal has to travel through this ceramic when re-entering the transducer.

**Comment by dansteingart** [comment]
Is the action item to 1) find the real zero point or 2) just allow us to set the delay?

**Comment by dansteingart** [comment]
Closing: open if there's a bug associated here
